// <auto-generated />
using System;
using DotNetCoreSqlDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCoreSqlDb.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20230808123849_UpdateSiteColumns")]
    partial class UpdateSiteColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCoreSqlDb.Models.Site", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AntalEnheter")
                        .HasColumnType("int");

                    b.Property<string>("Epostadress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GammalAdressEfterFlytt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gatuadress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISSKontorSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kommentarer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktNamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leverantör")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobilnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NätverkskapacitetGbps")
                        .HasColumnType("int");

                    b.Property<int?>("NätverkskapacitetMbps")
                        .HasColumnType("int");

                    b.Property<string>("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteTyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sitestorlek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WANUplink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Site");
                });
#pragma warning restore 612, 618
        }
    }
}
